version: '3.8'

services:
  php_apache_environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./public:/var/www/html
      - ./backend:/var/www/html/backend
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - jenkins
    environment:
      - TZ=America/Sao_Paulo
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BoiDataBase
      MYSQL_DATABASE: registro_carros
      MYSQL_PASSWORD: BoiDataBase
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pBoiDataBase"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s
    networks:
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: docker/Dockerfile.jenkins
    container_name: jenkins-blueocean
    networks:
      - jenkins
      - app-network
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      - TZ=America/Sao_Paulo
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/project
    ports:
      - "8081:8080"
      - "50000:50000"
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge
  jenkins:
    name: jenkins
    driver: bridge

volumes:
  db_data:
    name: mysql-data
  jenkins-data:
    name: jenkins-data
